# Java Maven CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: <command>
  test:
    docker:
      - image: circleci/openjdk:8-jdk
      
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - run: mvn -U dependency:go-offline compile
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
