spring:
  application:
    name: feign-client

server:
  port: 8762

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
       defaultZone: http://127.0.0.1:8760/eureka/
  instance:
    hostname: localhost